# Generated by Django 5.2.17 on 2026-08-24 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("symbol", models.CharField(max_length=8)),
                ("decimal_places", models.PositiveSmallIntegerField(default=2)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("rate", models.DecimalField(decimal_places=12, max_digits=24)),
                ("source", models.CharField(default="manual", max_length=64)),
                (
                    "base_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="base_rates",
                        to="core.currency",
                    ),
                ),
                (
                    "quote_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_rates",
                        to="core.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "base_currency", "quote_currency", "source"),
                        name="unique_fx_rate",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("base_currency", models.F("quote_currency")), _negated=True
                        ),
                        name="fx_currencies_differ",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate__gt", 0)), name="fx_rate_positive"
                    ),
                ],
            },
        ),
    ]
