# Generated by Django 5.2.17 on 2026-08-24 12:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=24)),
                ("name", models.CharField(max_length=160)),
                (
                    "security_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stock"),
                            ("ETF", "ETF"),
                            ("FUND", "Fund"),
                            ("BOND", "Bond"),
                            ("CRYPTO", "Crypto"),
                            ("CASH_EQUIVALENT", "Cash equivalent"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("isin", models.CharField(blank=True, max_length=12)),
                ("exchange", models.CharField(blank=True, max_length=64)),
                ("active", models.BooleanField(default=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.currency"
                    ),
                ),
            ],
            options={
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=24)),
                ("price_per_unit", models.DecimalField(decimal_places=8, max_digits=20)),
                ("gross_amount", models.DecimalField(decimal_places=4, max_digits=20)),
                ("fees", models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ("taxes", models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                (
                    "exchange_rate",
                    models.DecimalField(blank=True, decimal_places=12, max_digits=24, null=True),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.currency"
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investment_detail",
                        to="ledger.transaction",
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="investments.security"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SecurityPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("source", models.CharField(default="manual", max_length=64)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.currency"
                    ),
                ),
                (
                    "security",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="investments.security",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddConstraint(
            model_name="security",
            constraint=models.UniqueConstraint(
                fields=("symbol", "exchange"), name="unique_security_symbol_exchange"
            ),
        ),
        migrations.AddConstraint(
            model_name="securityprice",
            constraint=models.UniqueConstraint(
                fields=("security", "date", "source"), name="unique_security_price"
            ),
        ),
    ]
