# Generated by Django 5.2.17 on 2026-08-24 13:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("CHECKING", "Checking"),
                    ("SAVINGS", "Savings"),
                    ("FIXED_TERM", "Fixed Term Deposit"),
                    ("CASH", "Cash"),
                    ("BROKERAGE", "Brokerage"),
                    ("CREDIT_CARD", "Credit card"),
                    ("LOAN", "Loan"),
                    ("MORTGAGE", "Mortgage"),
                    ("CRYPTO", "Crypto"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FixedTermDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "principal",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0.0001)],
                    ),
                ),
                ("start_date", models.DateField()),
                ("maturity_date", models.DateField()),
                (
                    "annual_interest_rate",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "interest_method",
                    models.CharField(
                        choices=[("SIMPLE", "Simple Interest"), ("COMPOUND", "Compound Interest")],
                        max_length=10,
                    ),
                ),
                (
                    "compounding_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAILY", "Daily"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "interest_payment_method",
                    models.CharField(
                        choices=[
                            ("AT_MATURITY", "At maturity"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUALLY", "Annually"),
                        ],
                        default="AT_MATURITY",
                        max_length=16,
                    ),
                ),
                (
                    "interest_destination",
                    models.CharField(
                        choices=[
                            ("CAPITALIZED", "Added to principal"),
                            ("PAID_OUT", "Paid to another account"),
                        ],
                        default="CAPITALIZED",
                        max_length=12,
                    ),
                ),
                ("early_withdrawal_allowed", models.BooleanField(default=False)),
                ("early_withdrawal_penalty_notes", models.TextField(blank=True)),
                (
                    "maturity_instruction",
                    models.CharField(
                        choices=[
                            ("RETURN_TO_ACCOUNT", "Return funds"),
                            ("RENEW_PRINCIPAL", "Renew principal"),
                            ("RENEW_PRINCIPAL_AND_INTEREST", "Renew principal and interest"),
                            ("UNDECIDED", "Undecided"),
                        ],
                        default="UNDECIDED",
                        max_length=32,
                    ),
                ),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_term_details",
                        to="accounts.financialaccount",
                    ),
                ),
                (
                    "interest_destination_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_term_interest_destinations",
                        to="accounts.financialaccount",
                    ),
                ),
                (
                    "maturity_destination_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_term_maturity_destinations",
                        to="accounts.financialaccount",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "fixed term details",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("principal__gt", 0)), name="fixed_principal_gt_zero"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("annual_interest_rate__gte", 0)),
                        name="fixed_rate_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("maturity_date__gt", models.F("start_date"))),
                        name="fixed_maturity_after_start",
                    ),
                ],
            },
        ),
    ]
