# Generated by Django 5.2.17 on 2026-08-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_financialaccount_account_type_fixedtermdetails'),
        ('tax', '0002_returntaxtreatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='return_tax_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='tax.returntaxtreatment'),
        ),
    ]
