# Generated by Django 5.2.17 on 2026-08-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jurisdiction", models.CharField(max_length=8)),
                ("tax_year", models.PositiveIntegerField()),
                ("rule_type", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=120)),
                (
                    "rate",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
                ),
                (
                    "threshold",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "lower_bound",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                (
                    "upper_bound",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
