# Generated by Django 5.2.17 on 2026-08-25 11:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnTaxTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('treatment_type', models.CharField(choices=[('NONE', 'No Tax'), ('WITHHOLDING', 'Withholding Tax'), ('YEAR_END', 'Taxable at Year End'), ('EXEMPT', 'Tax Exempt'), ('CUSTOM', 'Custom Tax Rate')], max_length=16)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage rate: 15.00 means 15%.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('jurisdiction', models.CharField(blank=True, max_length=2)),
                ('tax_deducted_at_source', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_tax_treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_return_tax_treatment_per_owner')],
            },
        ),
    ]
